# Nome do projeto Docker Compose
name: pocket-js-server

services:
  # Serviço do PostgreSQL
  pg:
    # Imagem do PostgreSQL a ser usada
    image: bitnami/postgresql:13.16.0
    # Mapeamento de portas: porta 5432 do host para a porta 5432 do container
    ports:
      - "5432:5432"
    # Variáveis de ambiente para configurar o PostgreSQL
    environment:
      - POSTGRESQL_USER=docker       # Nome de usuário do PostgreSQL
      - POSTGRESQL_PASSWORD=docker   # Senha do PostgreSQL
      - POSTGRESQL_DATABASE=inorbit  # Nome do banco de dados PostgreSQL